### ISSUE TITLE
FR: Sync to main (default) calendar

### ISSUE THREAD

**Issue by arkenoi** [bergercookie/taskw_gcal_sync#16]
Now if I try to do it tw_gcal_sync just adds a new calendar with the same name

**Comment by bergercookie** [comment]
Hi there @arkenoi ,

I'm not sure what the reason for this may be for this but this tool was originally designed to sync with an entirely new calendar. Also, I consider syncing to your main calendar a bad practice since then there's no way of doing a full sync again, i.e., you can't just delete the whole calendar + taskw_gcal_sync local configuration and rerun it from scratch.

Even more, this is a defense mechanism. What if this plugin screws up and deletes something that it shouldn't? Or what if you accidentally add multiple unwanted tasks to taskwarrior and they get synced to your calendar. there's no way of undoing it. While in a seperate calendar you can just delete config+calendar and start again.

AFAICT there's no compelling reason for having this as a feature. Marking as won't do.
