### ISSUE TITLE
Google Authentication blocked

### ISSUE THREAD

**Issue by narudarurarasya** [bergercookie/taskw_gcal_sync#24]
Hello, while trying to fetch credentials when trying to setup for the first time, I see this error.

![app_blocked](https://user-images.githubusercontent.com/6368653/113037696-f286b080-9195-11eb-98f5-5131221d95da.png)

Any idea how can this be now solved? :)

Cheers

**Comment by bergercookie** [comment]
Yeah, I've hit Google's 100 users app and I think that's why you're getting that screen :/

I've contacted Google to verify my application so hopefully I'll deal with this in the coming weeks.
In the meantime, you can create your own dev application on Google Developers and substitute my embedded client key with a newly generated one. You can find my key under taskw_gcal_sync/res//gcal_client_secret.json, and you can follow the instructions of this page for creating an application that utilises the Google Calendar API:

https://github.com/insanum/gcalcli#login-information

**Comment by narudarurarasya** [comment]
Thanks, will try this. :)
